# @package _group_
EarlyStopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${trainer.metric}
  min_delta: 0.0001
  patience: 10
  mode: ${trainer.mode}
  
ModelCheckpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${trainer.metric}
  save_top_k: 3
  save_last: True
  dirpath: tmp
  filename: model-{epoch}
  mode: ${trainer.mode}