EarlyStopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${trainer.metric}
  min_delta: 0.0001
  patience: 10
  mode: ${trainer.mode}
ProgressBar:
  #_target_: pytorch_lightning.callbacks.RichProgressBar # VSCodeでRichProgressBarを使うと遅いので注意
  _target_: pytorch_lightning.callbacks.RichProgressBar
  refresh_rate: 50
  leave: False
  #process_position: 0
ModelCheckpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${trainer.metric}
  save_top_k: 3
  save_last: True
  dirpath: tmp
  filename: model-{epoch}
  mode: ${trainer.mode}