# @package _global_
optuna:
    instance:
        _target_:
    net:
        z_dim: 
            min: 2
            max: 6
        n_layers:
            min: 1
            max: 4
        dropout:
            min: 0.0
            max: 0.0
        hidden_size:
            min: 4
            max: 12
    optimizer:
        lr:
            min: 1e-6
            max: 1e-2
    study:
        direction: 'minimize'
        study_name: ${model.name}_${data.name}
        storage: sqlite:///optuna_runs/${optuna.study.study_name}.db 
    optimize:
        n_trials: 200
        #n_jobs: -1
trainer:
    max_epochs: 100
    use_logger: False
    use_model_checkpoint: False
model:
    optuna: ${optuna}