# @package _global_
logger:
    _target_: pytorch_lightning.loggers.MLFlowLogger
    experiment_name: example
    tracking_uri: http://g21.heroz.local:5000/
    save_dir: ./mlruns
    artifact_location : ./mlruns